steps:
  - name: node:16
    entrypoint: npm
    args: ["install"]
    dir: "frontend"
    id: "install-frontend"
    waitFor: ["-"]
  - name: node:16
    entrypoint: npm
    args: ["run", "build"]
    dir: "frontend"
    id: "build-frontend"
    waitFor: ["install-frontend"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "frontend"
    id: "deploy-frontend"
    waitFor: ["install-frontend", "build-frontend"]
  - name: node:16
    entrypoint: npm
    args: ["install"]
    dir: "server"
    id: "install-server"
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "server"
    id: "deploy-server"
    waitFor: ["install-server", "deploy-frontend"]